### model
model_name_or_path: meta-llama/Meta-Llama-3-8B-Instruct
adapter_name_or_path: saves/llama3-8b/full/sft

### method
finetuning_type: full

### dataset
task: mmlu
split: test
template: llama3
lang: en
n_shot: 5

### output
save_dir: saves/llama3-8b/full/eval/mmlu

### eval
batch_size: 4
